"""Backward-compatibility module forwarding to aarkib.services.media_service."""

from __future__ import annotations

from aarkib.services.media_service import (
    AUDIO_EXTENSIONS,
    BOOK_EXTENSIONS,
    MAX_DESCRIPTION_LENGTH,
    MAX_ISBN_LENGTH,
    MAX_LANGUAGE_LENGTH,
    MAX_PUBLISHER_LENGTH,
    MAX_TITLE_LENGTH,
    MEDIA_TYPE_CHOICES,
    VIDEO_EXTENSIONS,
    count_books_in_library,
    count_media_in_library,
    edit_book_metadata,
    edit_media_metadata,
    generate_slug,
    library_path_conditions,
    path_match_filter,
    path_prefixes,
    resolve_library,
    resolve_or_create_authors,
    resolve_or_create_collections,
    resolve_or_create_creators,
    resolve_or_create_series,
    resolve_or_create_tags,
)

__all__ = [
    "AUDIO_EXTENSIONS",
    "VIDEO_EXTENSIONS",
    "BOOK_EXTENSIONS",
    "MEDIA_TYPE_CHOICES",
    "MAX_TITLE_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_PUBLISHER_LENGTH",
    "MAX_LANGUAGE_LENGTH",
    "MAX_ISBN_LENGTH",
    "resolve_or_create_authors",
    "resolve_or_create_creators",
    "resolve_or_create_series",
    "resolve_or_create_collections",
    "resolve_or_create_tags",
    "edit_media_metadata",
    "edit_book_metadata",
    "generate_slug",
    "resolve_library",
    "path_prefixes",
    "library_path_conditions",
    "path_match_filter",
    "count_media_in_library",
    "count_books_in_library",
]
